version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: meu_usuario
      MYSQL_PASSWORD: minha_senha
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha-rede

  php-apache:
    build: .
    container_name: php_apache
    ports:
      - "8080:80"  # O Apache vai ouvir na porta 80, acessível pela porta 8080 no host
    volumes:
      - ./src:/var/www/html  # Mapeando a pasta src para o diretório do Apache
    depends_on:
      - mysql  # Garante que o MySQL será iniciado antes do PHP
    networks:
      - minha-rede

networks:
  minha-rede:

volumes:
  mysql_data:
